name: transformer
description: "api integration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  #for using api as links
  http: ^1.2.2

  #REST api for thingsboard dashboard
  thingsboard_client: ^2.0.0

  #history data graph
  fl_chart: ^0.69.1

  #firebase packages
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0

  #change notifier
  provider: ^6.1.2

  #mini storage
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  get: ^4.6.6
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.6
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/